### ISSUE TITLE
NameError: name 'time' is not defined And TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ydduong** [sirius777coder/ESM-Inpainting#13]
Hello, GPDL is an exciting project. Now, there are these two small error messages in the project.

1.
Traceback (most recent call last):
  File "./gpdl_hallucination/hallucination_v1.py", line 294, in <module>
    t_end=time.time()
NameError: name 'time' is not defined

2.
Traceback (most recent call last):
  File "./gpdl_hallucination/hallucination_v1.py", line 301, in <module>
    f.write(f'{fst_suc_step[i]}')
TypeError: a bytes-like object is required, not 'str'

**Comment by sirius777coder** [comment]
Thank you! It has been fixed now.

**Comment by ydduong** [comment]
Thanks!
